# Site settings
title: Rhytah-Portfolio
description: A little about myself
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rita Namono
user_description: Seasoned software developer that loves tinkering with computer languages to build solutions.
user_title: Software Developer
email: ritanamono@gmail.com
twitter_username: ritanamono
github_username:  Rhytah


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
